[build]
  command = "npm run build"
  publish = ".next"
  idiomatic_version_file_enable_tools = true

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "22.15.0"
  NPM_VERSION = "10.9.2"
  NEXT_USE_NETLIFY_EDGE = "true"
  NEXT_FORCE_EDGE_IMAGES = "true"

[functions]
  node_bundler = "esbuild"
  included_files = ["node_modules/@prisma/engines/**", "node_modules/.prisma/**"]

[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.images]
  compress = true

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' 'unsafe-eval' data: blob: https:; img-src 'self' data: blob: https:; connect-src 'self' https:; frame-ancestors 'none';" 